dataset: taskA/data/train_arousal.csv          # non usato in predict/evaluation
testset: taskA/data/test_arousal.csv           # TEST UFFICIALE con gold labels
target_col: A
model_save_path: taskA/risultati/model_arousal.pth

tokenizer:
  name: dbmdz/bert-base-italian-cased

training:
  epochs: 8
  batch_size: 16
  learning_rate: 0.00002 # 2e-5 viene scambiato per una stringa
  seed: 42
