dataset: taskA/data/train_valence.csv          # train (da Development set)
testset: taskA/data/val_valence.csv            # validation per early stopping (NON test ufficiale)
target_col: V
model_save_path: taskA/risultati/model_valence.pth

tokenizer:
  name: dbmdz/bert-base-italian-cased

training:
  epochs: 8
  batch_size: 16
  learning_rate: 0.00002 # 2e-5 viene scambiato per una stringa
  seed: 42